notARepository: 'skip'
customCommands:
  - key: 'C'
    context: 'files'
    prompts:
      - type: 'menu'
        title: 'Type'
        key: 'type'
        options:
          - name: 'feature'
            value: 'feature'
          - name: 'fix'
            value: 'fix'
          - name: 'chore'
            value: 'chore'
          - name: 'refactor'
            value: 'refactor'
          - name: 'lint'
            value: 'lint'
      - type: 'input'
        title: 'JIRA ticket id'
        key: 'ticketId'
      - type: 'input'
        title: 'Message'
        key: 'message'
    command: 'git commit -m "{{.Form.type}}: [{{.Form.ticketId}}] - {{.Form.message}}"'
