notARepository: 'skip'
git:
  paging:
    externalDiffCommand: difft --color=always
gui:
  switchTabsWithPanelJumpKeys: true
customCommands:
  - key: 'C'
    context: 'files'
    prompts:
      - type: 'menu'
        title: 'Type'
        key: 'type'
        options:
          - name: 'feature'
            value: 'feature'
          - name: 'fix'
            value: 'fix'
          - name: 'chore'
            value: 'chore'
          - name: 'refactor'
            value: 'refactor'
          - name: 'lint'
            value: 'lint'
      - type: 'input'
        title: 'Message'
        key: 'message'
    command: 'git commit -m "{{.Form.type}}: {{.Form.message}}"'
  - key: 'C'
    context: 'localBranches, remotes, remoteBranches'
    prompts:
      - type: 'menu'
        title: 'Type'
        key: 'type'
        options:
          - name: 'feature'
            value: 'feature'
          - name: 'bugfix'
            value: 'bugfix'
          - name: 'hotfix'
            value: 'hotfix'
          - name: 'chore'
            value: 'chore'
          - name: 'test'
            value: 'test'
      - type: 'input'
        title: 'JIRA ticket'
        key: 'ticketId'
      - type: 'input'
        title: 'Message'
        key: 'message'
    command: 'git checkout -b "{{.Form.type}}/{{if .Form.ticketId}}{{.Form.ticketId}}-{{end}}{{.Form.message}}"'
