notARepository: 'skip'
gui:
  switchTabsWithPanelJumpKeys: true
customCommands:
  - key: 'C'
    context: 'files'
    prompts:
      - type: 'menu'
        title: 'Type'
        key: 'type'
        options:
          - name: 'feature'
            value: 'feature'
          - name: 'fix'
            value: 'fix'
          - name: 'chore'
            value: 'chore'
          - name: 'refactor'
            value: 'refactor'
          - name: 'lint'
            value: 'lint'
      - type: 'menu'
        title: 'Module'
        key: 'module'
        options:
          - name: 'bag-loading'
            value: 'bag-loading'
          - name: 'bin-insertion'
            value: 'bin-insertion'
          - name: 'bin-inspection'
            value: 'bin-inspection'
          - name: 'picking'
            value: 'picking'
          - name: 'putaway'
            value: 'putaway'
          - name: 'route-collection'
            value: 'route-collection'
      - type: 'input'
        title: 'JIRA ticket id'
        key: 'ticketId'
      - type: 'input'
        title: 'Message'
        key: 'message'
    command: 'git commit -m "{{.Form.type}}: [{{.Form.ticketId}}] - {{.Form.message}}"'
